# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cd95a77dfb67729bde601e48b7f2fa4e94056822ed19d90a941441cefae17edf9cd05acb51da58f5057e7062e9c4043debc96e0ddc1048dec9949eea3261669

test:
  secret_key_base: dcbb2069597ffb2a829c23392db88fc9122172d25bd4a0e6d3c029b6ff3e9d83201ceb4b6ef77faafef7866814abb6bb10bf07c7fce07e4512117da12abd5bde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
